



Salle: Salle.o SalleCours.o SalleInfo.o ListeSalle.o 
	g++ Salle.o SalleCours.o SalleInfo.o ListeSalle.o  -o Salle

Salle.o: Salle.cpp Salle.h 
	g++ -c -g Salle.cpp

SalleCours.o:SalleCours.cpp Salle.h
	g++ -c -g SalleCours.cpp


SalleInfo.o:SalleInfo.cpp SalleInfo.h
	g++ -c -g SalleInfo.cpp


ListeSalle.o:ListeSalle.cpp ListeSalle.h
	g++ -c -g ListeSalle.cpp















