

Programmae: MatriceCarree.o MatriceAdj.o Graphe.o Sommet.o 
	g++ MatriceCarree.o MatriceAdj.o Graphe.o Sommet.o -o Programme

MatriceCarree.o: MatriceCarree.cpp MatriceCarree.h 
	g++ -c -g MatriceCarree.cpp

MatriceAdj.o:MatriceAdj.cpp MatriceAdj.h 
	g++ -c -g MatriceAdj.cpp


Graphe.o:Graphe.cpp Graphe.h 
	g++ -c -g Graphe.cpp


Sommet.o:Sommet.cpp Sommet.h
	g++ -c -g Sommet.cpp


