



Carte: Carte.o Partie.o Paquet.o Joueur.o ListeCartes.o
	g++ Carte.o Partie.o Paquet.o Joueur.o ListeCartes.o -o Carte

Carte.o: Carte.cpp Carte.h Paquet.h Joueur.h ListeCartes.h Partie.h
	g++ -c -g Carte.cpp

Partie.o:Partie.cpp Partie.h
	g++ -c -g Partie.cpp


Paquet.o:Paquet.cpp Paquet.h
	g++ -c -g Paquet.cpp


Joueur.o:Joueur.cpp Joueur.h
	g++ -c -g Joueur.cpp

ListeCartes.o:ListeCartes.cpp ListeCartes.h
	g++ -c -g ListeCartes.cpp














